title: Jekyll Zendesk Garden
description: A Jekyll theme using the Zendesk Garden design patterns
version: v0.1.0
permalink: pretty

plugins:
  - jekyll-postcss

whitelist:
  - jekyll-postcss

sidebar:
  - id: getting-started
  - label: Recipes
    children:
      - id: cookies
      - id: toast
