title: Zendesk Garden Jekyll Theme
description: A Jekyll theme using the Zendesk Garden design patterns
version: v0.2.0

permalink: pretty

search_enabled: true

sidebar:
  - getting-started
  - label: Recipes
    children:
      - cookies
      - toast

plugins:
  - jekyll-postcss

whitelist:
  - jekyll-postcss

exclude:
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .prettierrc
  - .prettierignore
  - .tool-versions
  - Gemfile
  - LICENSE*
  - node_modules
  - package.json
  - README
  - '*.gemspec'
  - '*.config.js'

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: default
