title: Jekyll Zendesk Garden
description: A Jekyll theme using the Zendesk Garden design patterns
version: v0.1.0
permalink: pretty

exclude:
  - node_modules
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - "*.config.js"

plugins:
  - jekyll-postcss
