title: Jekyll Zendesk Garden
description: A Jekyll theme using the Zendesk Garden design patterns
version: v0.2.0
permalink: pretty

plugins:
  - jekyll-postcss

whitelist:
  - jekyll-postcss

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

sidebar:
  - getting-started
  - label: Recipes
    children:
      - cookies
      - toast
