title: Zendesk Garden Jekyll Theme
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
version: v0.3.2

baseurl: /jekyll-theme-zendesk-garden

search_enabled: true

sidebar:
  - getting-started
  - label: Recipes
    children:
      - cookies
      - toast
