title: Jekyll - Zendesk Garden
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
version: v0.1.0

sidebar:
  - id: getting-started
  - id: recipes
    label: Recipes
    children:
      - id: cookies
      - id: toast
