title: Jekyll - Zendesk Garden
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
version: v0.1.0

defaults:
  - scope:
      path: ""
    values:
      layout: default

sidebar:
  - id: getting-started
  - label: Recipes
    children:
      - id: cookies
      - id: toast
