title: Serious Sidebar Jekyll Theme
remote_theme: Fede-Rausa/SeriousSidebarJekyll@main

baseurl: /SeriousSidebarJekyll

search_enabled: true
auto_page_title: true

version: 2.4.5
show_version: true
show_title: true
show_last_update_datetime: true

sidebar:
  - getting-started
  - label: Customization
    children:
      - sidebar
      - search
      - relative-nav
      - additional-config
  - development
