title: Serious Sidebar Jekyll Theme
version: 2.4.5
global_footnotes: written by Z.R.

remote_theme: Fede-Rausa/SeriousSidebarJekyll@main

baseurl: /SeriousSidebarJekyll

search_enabled: true
auto_page_title: true

link_to_github_repo: false
show_title: true
show_last_update_datetime: true
show_version: true
show_global_footnotes: true

sidebar:
  - getting-started
  - label: Customization
    children:
      - sidebar
      - search
      - relative-nav
      - additional-config
  - development
