title: Jekyll - Zendesk Garden
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
version: v0.1.0

baseurl: /jekyll-theme-zendesk-garden

sidebar:
  - getting-started
  - label: Recipes
    children:
      - cookies
      - toast
